# SPDX-FileCopyrightText: 2022 OPTIMETA and KOMET projects <https://projects.tib.eu/komet>
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Django settings for geodjango project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/

See also
https://djangocentral.com/environment-variables-in-django/
"""

import os
import re
import sys
from pathlib import Path

import dj_database_url
import environ

# .env file in the same directory as settings.py
env = environ.Env()
environ.Env.read_env()

# use this if setting up on Windows 10 with GDAL installed from OSGeo4W using defaults
if os.name == "nt":
    VIRTUAL_ENV_BASE = os.environ["VIRTUAL_ENV"]
    os.environ["PATH"] = os.path.join(VIRTUAL_ENV_BASE, r".\Lib\site-packages\osgeo") + ";" + os.environ["PATH"]
    os.environ["PROJ_LIB"] = (
        os.path.join(VIRTUAL_ENV_BASE, r".\Lib\site-packages\osgeo\data\proj") + ";" + os.environ["PATH"]
    )
    GDAL_LIBRARY_PATH = os.path.join(VIRTUAL_ENV_BASE, r".\Lib\site-packages\osgeo\gdal304.dll")
    GEOS_LIBRARY_PATH = os.path.join(VIRTUAL_ENV_BASE, r".\Lib\site-packages\osgeo\geos_c.dll")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("OPTIMAP_DEBUG", default=False)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ALLOWED_HOSTS = [i.strip("[]") for i in env("OPTIMAP_ALLOWED_HOST", default="*").split(",")]

OPTIMAP_SUPERUSER_EMAILS = [i.strip("[]") for i in env("OPTIMAP_SUPERUSER_EMAILS", default="").split(",")]

TEST_HARVESTING_ONLINE = env("OPTIMAP_TEST_HARVESTING_ONLINE", default=False)

# Reverse-geocoding via Nominatim (issue #222) — populates Work.placename and
# Work.country_code on save when geometry changes. Default is on in production
# (so the `geo.placename` / `geo.region` HTML meta tags are emitted and the
# Work.provenance.geocoding block is populated by every harvester); the
# 30-day per-coordinate LocMemCache absorbs repeat lookups so the 1 req/s
# Nominatim courtesy budget is rarely tested. Forced off under the test
# runner so the suite stays offline; opt out in a deployment by setting
# OPTIMAP_GEOCODE_WORKS_ON_SAVE=False (e.g. during a bulk import where you
# want to backfill placenames separately via `manage.py backfill_placenames`).
_RUNNING_TESTS = "test" in sys.argv or "pytest" in sys.modules or env("PYTEST_CURRENT_TEST", default="") != ""
GEOCODE_WORKS_ON_SAVE = env(
    "OPTIMAP_GEOCODE_WORKS_ON_SAVE",
    default=False if _RUNNING_TESTS else True,
)

ROOT_URLCONF = "optimap.urls"

DATA_DUMP_RETENTION = int(os.getenv("OPTIMAP_DATA_DUMP_RETENTION", 3))

# Feed configuration
FEED_CACHE_HOURS = int(os.getenv("OPTIMAP_FEED_CACHE_HOURS", 24))

# Ocean geometry simplification configuration
OCEAN_SIMPLIFICATION_TOLERANCE = float(os.getenv("OPTIMAP_OCEAN_SIMPLIFICATION_TOLERANCE", "0.05"))
OCEAN_SIMPLIFICATION_PERCENTILE = float(os.getenv("OPTIMAP_OCEAN_SIMPLIFICATION_PERCENTILE", "80.0"))

# Global regions data directory (for storing downloaded ocean/continent files)
# Default: <project_root>/works/management/commands (backwards compatible)
# For deployment: set to a non-volatile directory like /var/opt/optimap/data
GLOBAL_REGIONS_DATA_DIR = os.getenv("OPTIMAP_GLOBAL_REGIONS_DATA_DIR", None)

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# Login/Logout URLs for @login_required decorator
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django.contrib.sitemaps",
    "django.contrib.humanize",
    "works",
    "rest_framework",
    "rest_framework_gis",
    "django_q",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "leaflet",
    "import_export",
    "meta",
]


# django-meta — emits Open Graph, Twitter Card, and schema.org JSON-LD tags
# from Meta objects passed in the template context. See works/seo.py for the
# OPTIMAP-side helpers and base.html for the include site.
META_SITE_PROTOCOL = env("OPTIMAP_META_SITE_PROTOCOL", default="http")
META_SITE_DOMAIN = env("OPTIMAP_META_SITE_DOMAIN", default="localhost:8000")
META_SITE_NAME = "OPTIMAP"
META_DEFAULT_KEYWORDS = [
    "geospatial",
    "open access",
    "research articles",
    "metadata",
    "OPTIMAP",
    "KOMET",
]
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True
META_USE_SCHEMAORG_PROPERTIES = True
META_USE_JSON_LD_SCHEMA = True  # emit `<script type="application/ld+json">`
META_DEFAULT_TYPE = "website"
META_USE_SITES = False  # we set domain/protocol via META_SITE_* above
META_USE_TITLE_TAG = False  # templates render their own <title>
META_INCLUDE_KEYWORDS = ["geospatial", "OPTIMAP", "KOMET"]

AUTH_USER_MODEL = "works.CustomUser"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "works.pagination.LinkHeaderPagination",
    "PAGE_SIZE": 999,
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
# https://pypi.org/project/dj-database-url/
DATABASES = {
    "default": dj_database_url.config(  # this uses DATABASE_URL environment variable
        # value must be URL-encoded: postgres://user:p%23ssword!@localhost/foobar
        default="postgis://optimap:optimap@localhost:5432/optimap",
        conn_max_age=600,
    )
}

# https://github.com/tfranzel/drf-spectacular
SPECTACULAR_SETTINGS = {
    "TITLE": "OPTIMAP API",
    "DESCRIPTION": """
OPTIMAP is a geospatial discovery portal for scientific works. The API exposes the same
data that powers the OPTIMAP web UI: harvested **works** with spatial / temporal metadata,
**sources** that fed them, **collections** they belong to, **subscriptions** that drive email
alerts, and helper services for **geoextent extraction** and **gazetteer** lookups.

The OpenAPI schema this page is built from is at [`/api/schema/`](/api/schema/) (YAML, served
without auth). The UI is rendered by [Redoc](https://github.com/Redocly/redoc) from drf-spectacular.

## Conventions

- **Base URL:** REST endpoints are rooted at `/api/v1/`. The global bulk downloads below are an
  exception — they sit directly under `/download/` without the `/api/v1/` prefix.
- **Anonymous reads:** `Works`, `Sources`, `Global regions`, `Geoextent`, `Gazetteer`, and the
  feed / download endpoints accept anonymous GETs. `Subscriptions` requires session auth.
- **Pagination:** list endpoints return a `{count, next, previous, results}` envelope with
  the default page size from `REST_FRAMEWORK['PAGE_SIZE']`. Use `?limit=` for explicit page
  size, `?offset=` to skip records.
- **Spatial filtering:** list endpoints with a geometry field accept `?in_bbox=west,south,east,north`
  (longitude/latitude in EPSG:4326).
- **GeoJSON envelope:** `Works` responses are valid GeoJSON `FeatureCollection`s; the OPTIMAP
  fields live under `properties` of each `Feature`. The `Content-Type` is `application/geo+json`
  per [W3C SDW-BP 5](https://www.w3.org/TR/sdw-bp/#BP5).
- **Coordinates** follow [GeoJSON RFC 7946](https://www.rfc-editor.org/rfc/rfc7946) axis order
  (longitude, latitude) in WGS 84 / EPSG:4326. Coordinate values are capped at **5 decimal places**
  (≈ 1.1 m at the equator) to reflect the actual accuracy of harvested spatial metadata
  ([W3C SDW-BP 6](https://www.w3.org/TR/sdw-bp/#BP6) and
  [BP 16](https://www.w3.org/TR/sdw-bp/#BP16)).
- **CSRF:** browser POST/PUT/DELETE requests need the `X-CSRFToken` header. Server-side scripts
  with session cookies should also fetch a CSRF token first.

## Bulk downloads

The full corpus is available as flat-file dumps (regenerated every 6 h):

| Endpoint | Format | Notes |
| -- | -- | -- |
| [`/download/geojson/`](/download/geojson/) | GeoJSON `FeatureCollection` | Gzipped when the client sends `Accept-Encoding: gzip` |
| [`/download/geopackage/`](/download/geopackage/) | OGC GeoPackage (`.gpkg`) | Single layer `works`, EPSG:4326 |
| [`/download/csv/`](/download/csv/) | CSV with WKT geometry column | UTF-8, RFC 4180 |

These are documented in the *Downloads* section below.

## Feeds (machine-readable)

GeoRSS / GeoAtom feeds are produced by the Django syndication framework and consumed by feed
readers. They are not full REST endpoints and therefore do not appear in the schema below.

### Global and region-filtered feeds

| URL | Format | Scope |
| -- | -- | -- |
| `/api/v1/feeds/optimap-global.rss` | GeoRSS 2.0 | All published works |
| `/api/v1/feeds/optimap-global.atom` | GeoAtom | All published works |
| `/api/v1/feeds/optimap-<continent-slug>.rss` / `.atom` | GeoRSS / GeoAtom | Continent-filtered (e.g. `optimap-africa.rss`) |
| `/api/v1/feeds/optimap-<ocean-slug>.rss` / `.atom` | GeoRSS / GeoAtom | Ocean-filtered (e.g. `optimap-pacific-ocean.rss`) |

Continent and ocean slugs match `GlobalRegion.identifier`; list them via
[`/api/v1/global-regions/`](/api/v1/global-regions/).

### Collection feeds

| URL | Format | Scope |
| -- | -- | -- |
| `/api/v1/feeds/collection-<collection-slug>.rss` | GeoRSS 2.0 | Published works in the collection |
| `/api/v1/feeds/collection-<collection-slug>.atom` | GeoAtom | Published works in the collection |

Collection slugs match `Collection.identifier`; list all published collections via
[`/api/v1/collections/`](/api/v1/collections/). Each collection response embeds the feed and
download URLs directly.
""".strip(),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/v1",  # strips the redundant "v1_" prefix from operationIds
    "TAGS": [
        {
            "name": "Works",
            "description": "Harvested scientific works with spatial / temporal metadata, returned as GeoJSON.",
        },
        {
            "name": "Sources",
            "description": "Configured harvest origins (OAI-PMH endpoints, RSS feeds, OpenAlex sources, etc.).",
        },
        {
            "name": "Subscriptions",
            "description": "Per-user regional subscriptions that drive email alerts. Session auth required.",
        },
        {"name": "Global regions", "description": "Continent and ocean polygons used by feeds and subscriptions."},
        {
            "name": "Geoextent",
            "description": "Extract a spatial / temporal extent from an uploaded file or a remote DOI/URL. Powered by the [geoextent](https://nuest.github.io/geoextent/) Python library.",
        },
        {
            "name": "Gazetteer",
            "description": "Server-side proxy for forward / reverse geocoding via Nominatim or Photon.",
        },
        {"name": "Downloads", "description": "Flat-file dumps of the full work corpus (GeoJSON, GeoPackage, CSV)."},
        {
            "name": "Collections",
            "description": "Curated groups of published works. The list/detail endpoints return collection metadata with a `works_count` and embedded links to feeds and downloads. Per-collection GeoRSS/GeoAtom feeds are served by the Django syndication framework and are documented in the API description above.",
        },
        {
            "name": "Body of Knowledge",
            "description": "Search the cached [EO4GEO Body of Knowledge](https://geospacebok.eu) for concept tagging.",
        },
        {
            "name": "Statistics",
            "description": "Cached aggregate counts for works, sources, collections, and users. Refreshed every 24 h.",
        },
    ],
    "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    # https://github.com/Redocly/redoc#redoc-options-object
    "REDOC_UI_SETTINGS": {
        # https://github.com/Redocly/redoc#redoc-theme-object
        "theme": {
            "sidebar": {
                # 'backgroundColor': '#ff0000',
            },
            "colors": {
                "primary": {"main": "#158F9B", "light": "#B9F0F6"},
                "http": {"get": "#158F9B", "post": "#3C159B", "put": "#3C159B", "delete": "#9B2115"},
                "success": {"main": "#158F9B", "light": "#9B7115", "dark": "#3C159B", "contrastText": "#000"},
                "text": {"primary": "rgba(0, 0, 0, 1)", "secondary": "#158F9B"},
            },
            "typography": {
                "heading1": {
                    "color": "#158F9B",
                },
                "heading2": {
                    "color": "#158F9B",
                },
                "heading3": {
                    "color": "#158F9B",
                },
                "links": {"color": "#158F9B", "visited": "#158F9B", "hover": "#3C159B"},
            },
        }
    },
}

Q_CLUSTER = {
    "name": "optimap",
    "workers": 1,
    "timeout": 60 * 10,  # seconds, must be less than retry
    "retry": 60 * 11,
    "save_limit": 0,  # unlimited
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
    "max_attempts": 5,
}

CACHES = {
    # Default: persists across processes (login tokens, email confirmations,
    # GeoRSS feed bodies). See https://docs.djangoproject.com/en/4.1/topics/cache/
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache",
    },
    # Per-process in-memory cache for hot anonymous reads — view-level
    # @cache_page decorators on static / low-change pages (feeds list,
    # sitemap, robots, privacy, …) and the work_landing context cache.
    # Each gunicorn worker keeps its own copy; first hit per worker is a
    # miss, subsequent hits are pure dict lookups (no DB roundtrip).
    "memory": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "optimap-locmem",
    },
    # Use for development to disable caching entirely (OPTIMAP_CACHE=dummy).
    "dummy": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    },
    #'redis': {
    #    "BACKEND": "django_redis.cache.RedisCache",
    #    "LOCATION": "redis://127.0.0.1:6379/1",
    #    "OPTIONS": {
    #        "CLIENT_CLASS": "django_redis.client.DefaultClient",
    #    },
    # }
}

BASE_DIR = Path(__file__).resolve().parent.parent

FIXTURE_DIRS = [
    BASE_DIR / "fixtures",
]

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"  # store session data in database, it's persistent and fast enough for us

CACHE_MIDDLEWARE_ALIAS = env("OPTIMAP_CACHE", default="default")
CACHE_MIDDLEWARE_SECONDS = env("OPTIMAP_CACHE_SECONDS", default=3600)

# Per-view cache TTLs for the in-process `memory` cache backend.
# Long: truly static pages (privacy, about, sitemap XML).
# Short: low-change pages that vary slightly over time (robots, feeds, geoextent).
PAGE_CACHE_LONG = env("OPTIMAP_PAGE_CACHE_LONG", default=86400)  # 24 h
PAGE_CACHE_SHORT = env("OPTIMAP_PAGE_CACHE_SHORT", default=3600)  # 1 h

# for testing email sending EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = env("OPTIMAP_EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("OPTIMAP_EMAIL_HOST", default="optimap.dev")
EMAIL_PORT = env("OPTIMAP_EMAIL_PORT_SMTP", default=587)
EMAIL_HOST_IMAP = env("OPTIMAP_EMAIL_HOST_IMAP", default="optimap.imap")
EMAIL_PORT_IMAP = env("OPTIMAP_EMAIL_PORT_IMAP", default=993)
EMAIL_HOST_USER = env("OPTIMAP_EMAIL_HOST_USER", default="optimap@dev")
EMAIL_HOST_PASSWORD = env("OPTIMAP_EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env("OPTIMAP_EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env("OPTIMAP_EMAIL_USE_SSL", default=False)
BASE_URL = env("OPTIMAP_BASE_URL", default="http://localhost:8000")
EMAIL_IMAP_SENT_FOLDER = env("OPTIMAP_EMAIL_IMAP_SENT_FOLDER", default="")
OPTIMAP_EMAIL_SEND_DELAY = env("OPTIMAP_EMAIL_SEND_DELAY", default=2)
BASE_URL = env("BASE_URL", default="http://127.0.0.1:8000")
EMAIL_SEND_DELAY = 2
DATA_DUMP_INTERVAL_HOURS = 6
INACTIVITY_WARNING_DAYS = env.int("OPTIMAP_INACTIVITY_WARNING_DAYS", default=365)
INACTIVITY_DELETION_DAYS = env.int("OPTIMAP_INACTIVITY_DELETION_DAYS", default=396)

# Contact email for API user agents (OpenAlex, Wikidata, etc.)
CONTACT_EMAIL = "login@optimap.science"

# Wikibase/Wikidata configuration
WIKIBASE_API_URL = env("WIKIBASE_API_URL", default="")

# OAuth 1.0a authentication (required)
WIKIBASE_CONSUMER_TOKEN = env("WIKIBASE_CONSUMER_TOKEN", default="")
WIKIBASE_CONSUMER_SECRET = env("WIKIBASE_CONSUMER_SECRET", default="")
WIKIBASE_ACCESS_TOKEN = env("WIKIBASE_ACCESS_TOKEN", default="")
WIKIBASE_ACCESS_SECRET = env("WIKIBASE_ACCESS_SECRET", default="")

# Property auto-creation setting
WIKIBASE_CREATE_PROPERTIES_IF_MISSING = env("WIKIBASE_CREATE_PROPERTIES_IF_MISSING", default=True, cast=bool)

# Import optimap version for user agent
import optimap

# Single User-Agent string used by every outbound request that doesn't have a
# specific upstream contract requiring a different shape (the only carve-out
# today is WIKIBASE_USER_AGENT below, which preserves the wikibase library's
# expected formatting). Includes the running release version, project URL,
# and a contact mailto so upstream operators can identify our traffic and
# reach us if there's a problem. Append a workflow qualifier at the call
# site (e.g. `f"{settings.OPTIMAP_USER_AGENT} preview"`) when it's useful
# for log diagnostics.
OPTIMAP_USER_AGENT = f"OPTIMAP/{optimap.__version__} (+http://optimap.science; mailto:{CONTACT_EMAIL})"
WIKIBASE_USER_AGENT = f"OPTIMAP/{optimap.__version__} (http://optimap.science; {CONTACT_EMAIL})"

# OAI-PMH harvesting settings
# 90s accommodates slow endpoints (e.g. EarthArXiv ListRecords takes >30s for full history)
OPTIMAP_OAI_HTTP_TIMEOUT = int(os.getenv("OPTIMAP_OAI_HTTP_TIMEOUT", 90))


# Geoextent API settings
GEOEXTENT_MAX_FILE_SIZE_MB = int(os.getenv("OPTIMAP_GEOEXTENT_MAX_FILE_SIZE_MB", 100))
GEOEXTENT_PROCESSING_TIMEOUT_SECONDS = int(os.getenv("OPTIMAP_GEOEXTENT_TIMEOUT", 30))
GEOEXTENT_TEMP_DIR = os.getenv("OPTIMAP_GEOEXTENT_TEMP_DIR", "/tmp/optimap_geoextent")

# Download limits - server-enforced maximums that cap user requests
GEOEXTENT_MAX_DOWNLOAD_SIZE_MB = int(os.getenv("OPTIMAP_GEOEXTENT_MAX_DOWNLOAD_SIZE_MB", 1000))
GEOEXTENT_MAX_BATCH_SIZE_MB = int(os.getenv("OPTIMAP_GEOEXTENT_MAX_BATCH_SIZE_MB", 500))

# Download workers for parallel processing (remote and batch operations)
GEOEXTENT_DOWNLOAD_WORKERS = int(os.getenv("OPTIMAP_GEOEXTENT_DOWNLOAD_WORKERS", 4))

# Placename/gazetteer settings
GEOEXTENT_DEFAULT_GAZETTEER = os.getenv("OPTIMAP_GEOEXTENT_DEFAULT_GAZETTEER", "nominatim")
GEOEXTENT_GAZETTEER_TIMEOUT_SECONDS = int(os.getenv("OPTIMAP_GEOEXTENT_GAZETTEER_TIMEOUT_SECONDS", 5))

# GeoNames API configuration (if using geonames gazetteer)
GEOEXTENT_GEONAMES_USERNAME = os.getenv("OPTIMAP_GEOEXTENT_GEONAMES_USERNAME", "")

# NER (Named Entity Recognition) text extraction settings.
# GEOEXTENT_NER_MODEL: spaCy model name. None = geoextent auto-selects and
#   downloads the default model on first use (~12 MB, one-off).
# GEOEXTENT_NER_GAZETTEER: default gazetteer for text-based NER extraction.
#   Separate from GEOEXTENT_DEFAULT_GAZETTEER so NER can use a different
#   service than the file-upload gazetteer.
GEOEXTENT_NER_MODEL = os.getenv("OPTIMAP_GEOEXTENT_NER_MODEL", None)
GEOEXTENT_NER_GAZETTEER = os.getenv("OPTIMAP_GEOEXTENT_NER_GAZETTEER", "nominatim")

# How long copied geometries from the geoextent tool ("Copy extents")
# remain available for paste into a work's contribution form. Stored
# client-side in localStorage; the work landing page silently discards
# anything older than this. Intentionally not env-var configurable —
# change in code only (small UX number, no per-deploy reason to tune).
GEOEXTENT_COPY_TTL_SECONDS = 5 * 60

# Geometry upload limits — enforced client-side before the POST is sent.
# GEOMETRY_WARN_SIZE_KB:  soft warning shown when a single polygon exceeds this.
# GEOMETRY_MAX_UPLOAD_KB: hard block shown at submit time if total payload exceeds this.
GEOMETRY_WARN_SIZE_KB = int(os.getenv("OPTIMAP_GEOMETRY_WARN_SIZE_KB", 50))
GEOMETRY_MAX_UPLOAD_KB = int(os.getenv("OPTIMAP_GEOMETRY_MAX_UPLOAD_KB", 2048))

# Seconds to sleep between geoextent calls in the GeoScienceWorld harvester.
# Each call fetches a GSW landing page via Cloudflare bypass (curl_cffi); a
# small delay reduces the risk of rate-limiting. Set to 0 to disable.
GEOSCIENCEWORLD_THROTTLE_SECONDS = float(os.getenv("OPTIMAP_GSW_THROTTLE", 2.0))

# EO4GEO Body of Knowledge — controlled vocabulary used for concept tagging
# on the work landing page. The cached snapshot lives in the `default` cache
# (DB-backed, lazy on miss) and is refreshed by `manage.py refresh_bok_snapshot`.
# Set to "v9", "v3", … (see https://eo4geo-uji.web.app/documentation/API.pdf).
# v9 is the current live version (1212 concepts, verified 2026-06-11).
# Firebase also exposes a "current" alias — we pin explicitly to avoid silent
# drift if the upstream alias moves.  v9 vs v3: expanded GC3 AI/ML hierarchy,
# new GN (GNSS) top-level category.
BOK_VERSION = os.getenv("OPTIMAP_BOK_VERSION", "v9")
BOK_API_BASE = os.getenv("OPTIMAP_BOK_API_BASE", "https://eo4geo-bok.firebaseio.com")
BOK_CONCEPT_BASE_URL = os.getenv("OPTIMAP_BOK_CONCEPT_BASE_URL", "https://geospacebok.eu")
# Gate: comma-separated list of `Collection.identifier` slugs (e.g.
# "mountain-wetlands,essd"). The BoK editor is restricted to works that
# belong to at least one of those collections; the `/contribute-bok/`
# endpoint enforces the same rule with a 403. **Empty (default) = BoK
# editor disabled site-wide** — opt-in by listing the collections you
# want to enable. Read-only chips remain visible regardless.
BOK_ENABLED_COLLECTIONS = [s.strip() for s in os.getenv("OPTIMAP_BOK_ENABLED_COLLECTIONS", "").split(",") if s.strip()]

# Browser Referrer-Policy. Django's SecurityMiddleware defaults this to
# "same-origin", which strips the Referer on cross-origin requests — and the
# OpenStreetMap standard tile server (used by every map on this site) blocks
# clients with no Referer per https://wiki.openstreetmap.org/wiki/Referer .
# "strict-origin-when-cross-origin" sends just the origin to third parties
# (enough for OSM's identification requirement, no path leakage) and matches
# modern browser defaults.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Per Django's cache-framework docs, the canonical placement is:
#   UpdateCacheMiddleware  — outermost on the response side; sets
#                            Cache-Control + Expires headers and stores
#                            qualifying responses in the default cache.
#   SessionMiddleware      — must run *before* FetchFromCacheMiddleware
#                            so the cache key can vary on session.
#   FetchFromCacheMiddleware — short-circuits the view on cache hit.
# AuthenticationMiddleware is listed once; previously the file had a
# stray second copy (and a duplicate UpdateCache/CommonMiddleware/
# FetchFromCache trio above SessionMiddleware) — both removed.
MIDDLEWARE = [
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.cache.FetchFromCacheMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
    "django_currentuser.middleware.ThreadLocalUserMiddleware",
    "django.middleware.gzip.GZipMiddleware",
]

ROOT_URLCONF = "optimap.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["works/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "optimap.urls.site",
                "optimap.context_processors.get_version",
                "optimap.context_processors.gazetteer_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "optimap.wsgi.application"

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
# https://docs.djangoproject.com/en/4.1/ref/contrib/staticfiles/
STATIC_ROOT = "static/"
STATIC_URL = "/static/"
STATICFILES_DIRS = ["works/static"]

# serve static files with Django, not with a dedicated webserver: http://whitenoise.evans.io/en/stable/django.html
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)-9s %(asctime)s | %(module)-12s | %(message)s",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {  # passes on records when DEBUG is True
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {"level": "DEBUG", "class": "logging.StreamHandler", "formatter": "verbose"},
        "mail_admins": {
            "level": "WARNING",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "mail_admins"],
            "level": env("DJANGO_LOGGING_LEVEL", default="INFO"),
        },
        "works": {
            "handlers": ["console", "mail_admins"],
            "level": env("OPTIMAP_LOGGING_LEVEL", default="INFO"),
        },
        "django.request": {
            "handlers": ["mail_admins"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

IGNORABLE_404_URLS = (
    re.compile(r"\.(php|cgi|env)$"),
    re.compile(r"^/phpmyadmin/"),
    re.compile(r"wp-login$"),
    re.compile(r"(.*)/wp-includes/(.*)"),
    re.compile(r"^/(http|https)$"),
    re.compile(r"ads.txt$"),
    re.compile(r"^\.git"),
)

CSRF_TRUSTED_ORIGINS = [
    i.strip("[]") for i in env("CSRF_TRUSTED_ORIGINS", default="https://localhost:8000").split(",")
]

ADMINS = [("OPTIMAP", "login@optimap.science")]

FEED_MAX_ITEMS = 100

# Gazetteer / Geocoding Settings
# Configures the location search (gazetteer) feature on the map
GAZETTEER_PROVIDER = env("OPTIMAP_GAZETTEER_PROVIDER", default="nominatim")
GAZETTEER_PLACEHOLDER = env("OPTIMAP_GAZETTEER_PLACEHOLDER", default="Search for a location...")
# Optional API key for commercial providers (not required for Nominatim)
GAZETTEER_API_KEY = env("OPTIMAP_GAZETTEER_API_KEY", default="")

# Default page size for paginated list views (works list, collection pages, etc.)
# OPTIMAP_WORKS_PAGE_SIZE_DEFAULT is kept as a fallback for backward compatibility.
PAGE_MAX_ITEMS = int(env("OPTIMAP_PAGE_MAX_ITEMS", default=env("OPTIMAP_WORKS_PAGE_SIZE_DEFAULT", default=50)))
# Works list pagination bounds (selectable range shown to users)
WORKS_PAGE_SIZE_DEFAULT = PAGE_MAX_ITEMS
WORKS_PAGE_SIZE_MIN = int(env("OPTIMAP_WORKS_PAGE_SIZE_MIN", default=10))
WORKS_PAGE_SIZE_MAX = int(env("OPTIMAP_WORKS_PAGE_SIZE_MAX", default=200))


# Calculate available page size options by doubling from MIN to MAX.
# Always includes MIN, MAX, and the given default value.
def _calculate_page_size_options(min_size, max_size, default=None):
    options = [min_size]
    current = min_size
    while current * 2 < max_size:
        current = current * 2
        options.append(current)
    if options[-1] != max_size:
        options.append(max_size)
    if default is not None and default not in options:
        options.append(default)
    return sorted(options)


WORKS_PAGE_SIZE_OPTIONS = _calculate_page_size_options(
    WORKS_PAGE_SIZE_MIN, WORKS_PAGE_SIZE_MAX, default=PAGE_MAX_ITEMS
)

# Number of works fetched per chunk when loading the main map.
OPTIMAP_MAP_CHUNK_SIZE = int(env("OPTIMAP_MAP_CHUNK_SIZE", default=500))

# OGC API - Features via pygeoapi (issue #19)
# Served at /ogcapi/ when etc/pygeoapi-config.yml is present and the
# etc/pygeoapi-openapi.yml has been generated (see manage.py generate_pygeoapi_openapi).
PYGEOAPI_ENABLED = False
_PYGEOAPI_CONFIG_PATH = Path(BASE_DIR) / "etc" / "pygeoapi-config.yml"
_PYGEOAPI_OPENAPI_PATH = Path(BASE_DIR) / "etc" / "pygeoapi-openapi.yml"
if _PYGEOAPI_CONFIG_PATH.exists() and _PYGEOAPI_OPENAPI_PATH.exists():
    os.environ.setdefault("PYGEOAPI_CONFIG", str(_PYGEOAPI_CONFIG_PATH))
    os.environ.setdefault("PYGEOAPI_OPENAPI", str(_PYGEOAPI_OPENAPI_PATH))
    try:
        from pygeoapi.config import get_config as _get_pygeoapi_config
        from pygeoapi.openapi import load_openapi_document as _load_openapi_document
        from pygeoapi.util import get_api_rules as _get_api_rules

        PYGEOAPI_CONFIG = _get_pygeoapi_config()
        OPENAPI_DOCUMENT = _load_openapi_document()
        API_RULES = _get_api_rules(PYGEOAPI_CONFIG)
        # Inject absolute templates path so custom templates are found regardless of cwd
        _pygeoapi_templates = Path(BASE_DIR) / "etc" / "pygeoapi-templates"
        if _pygeoapi_templates.is_dir():
            PYGEOAPI_CONFIG.setdefault("server", {}).setdefault("templates", {})
            PYGEOAPI_CONFIG["server"].setdefault("templates", {})["path"] = str(_pygeoapi_templates)
        PYGEOAPI_ENABLED = True
    except Exception as _pygeoapi_exc:
        import logging as _logging

        _logging.getLogger(__name__).warning("OGC API disabled: %s", _pygeoapi_exc)
