# SPDX-FileCopyrightText: 2026 OPTIMETA and KOMET projects <https://projects.tib.eu/komet>
# SPDX-License-Identifier: GPL-3.0-or-later

"""Tests for the source landing page (/in/<slug>/), per-source feeds, the
SourceCoverageSnapshot panel, and the /statistics/ links (issues #29, #253)."""

from django.contrib.gis.geos import GeometryCollection, Point
from django.test import Client, TestCase
from django.urls import reverse

from works.models import Source, SourceCoverageSnapshot, StatisticsSnapshot, Work


def _make_source(name, **kwargs):
    return Source.objects.create(name=name, url_field="https://example.org/oai", **kwargs)


def _pub(source, title, **kwargs):
    return Work.objects.create(status="p", title=title, source=source, **kwargs)


class SourceSlugTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        s = _make_source("Journal of Test Studies")
        self.assertEqual(s.slug, "journal-of-test-studies")
        self.assertEqual(s.get_absolute_url(), "/in/journal-of-test-studies/")

    def test_slug_unique_on_collision(self):
        a = _make_source("Same Name")
        b = _make_source("Same Name")
        self.assertNotEqual(a.slug, b.slug)
        self.assertTrue(b.slug.startswith("same-name"))

    def test_slug_truncated_to_max_length(self):
        max_length = Source._meta.get_field("slug").max_length
        long_name = "Long " * 40 + "X"  # fits name (255) but slugifies to >100 chars
        s = _make_source(long_name)
        self.assertLessEqual(len(s.slug), max_length)
        self.assertFalse(s.slug.endswith("-"))

    def test_slug_truncated_collision_stays_within_max_length(self):
        max_length = Source._meta.get_field("slug").max_length
        long_name = "Long " * 40 + "X"
        a = _make_source(long_name)
        b = _make_source(long_name)
        self.assertNotEqual(a.slug, b.slug)
        self.assertLessEqual(len(b.slug), max_length)


class SourcePageTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.source = _make_source("Scientific Data")
        self.work = _pub(self.source, "A published work", geometry=GeometryCollection(Point(1, 2)))
        # A non-published work must not appear.
        Work.objects.create(status="h", title="A harvested work", source=self.source)

    def test_page_lists_published_works(self):
        resp = self.client.get(reverse("optimap:in-source", kwargs={"source_slug": self.source.slug}))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "A published work")
        self.assertNotContains(resp, "A harvested work")
        # Feed links present.
        self.assertContains(resp, f"/api/v1/feeds/source-{self.source.slug}.rss")
        # Map present above the list (with the page/all scope toggle wiring).
        self.assertContains(resp, "facet-map")

    def test_unknown_slug_404(self):
        resp = self.client.get("/in/no-such-source/")
        self.assertEqual(resp.status_code, 404)

    def test_no_openalex_source_still_renders(self):
        """A source with no coverage snapshot shows the list, no coverage %."""
        resp = self.client.get(reverse("optimap:in-source", kwargs={"source_slug": self.source.slug}))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "No coverage snapshot yet")

    def test_coverage_panel_renders_snapshot(self):
        SourceCoverageSnapshot.objects.create(
            source=self.source,
            openalex_total=10,
            optimap_count=4,
            coverage_pct=40.0,
            spatial_rate=75.0,
            temporal_rate=50.0,
            open_access_ratio=25.0,
            contributors_count=3,
            by_year=[{"year": 2023, "count": 4}],
        )
        resp = self.client.get(reverse("optimap:in-source", kwargs={"source_slug": self.source.slug}))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "40.0%")  # coverage
        self.assertContains(resp, "75.0%")  # spatial rate
        self.assertNotContains(resp, "No coverage snapshot yet")

    def test_known_totals_without_snapshot(self):
        self.source.statistics = {"openalex_works_count": 123, "oai_works_count": 99}
        self.source.save(update_fields=["statistics"])
        resp = self.client.get(reverse("optimap:in-source", kwargs={"source_slug": self.source.slug}))
        self.assertContains(resp, "123")
        self.assertContains(resp, "Known totals")


class SourceFeedTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.source = _make_source("Feedy Journal")
        _pub(self.source, "Geo work", geometry=GeometryCollection(Point(3, 4)))
        # Works without geometry are excluded from the feed.
        _pub(self.source, "No-geo work")

    def test_georss_feed(self):
        resp = self.client.get(f"/api/v1/feeds/source-{self.source.slug}.rss")
        self.assertEqual(resp.status_code, 200)
        body = resp.content.decode()
        self.assertIn("Geo work", body)
        self.assertNotIn("No-geo work", body)

    def test_atom_feed(self):
        resp = self.client.get(f"/api/v1/feeds/source-{self.source.slug}.atom")
        self.assertEqual(resp.status_code, 200)


class StatisticsSourceLinkTests(TestCase):
    def test_statistics_links_to_source_page(self):
        source = _make_source("Linked Source")
        _pub(source, "w1")
        StatisticsSnapshot.objects.create()  # statistics page renders nothing without one
        SourceCoverageSnapshot.objects.create(source=source, openalex_total=10, optimap_count=1, coverage_pct=10.0)
        resp = Client().get(reverse("optimap:statistics"))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, f"/in/{source.slug}/")


class SourceIndexTests(TestCase):
    def test_in_index_lists_sources(self):
        source = _make_source("Indexed Journal")
        _pub(source, "w1")
        resp = Client().get(reverse("optimap:in-index"))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Indexed Journal")
        self.assertContains(resp, f"/in/{source.slug}/")


class StatisticsJournalLinkTests(TestCase):
    def test_statistics_by_journal_links_to_source(self):
        source = _make_source("Journaly")
        StatisticsSnapshot.objects.create(by_journal=[{"name": "Journaly", "count": 5}])
        resp = Client().get(reverse("optimap:statistics"))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, f"/in/{source.slug}/")


class SourceApiTests(TestCase):
    def test_source_api_exposes_landing_and_feed_urls(self):
        source = _make_source("Api Source")
        resp = Client().get(f"/api/v1/sources/{source.pk}/")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertEqual(data["slug"], source.slug)
        self.assertTrue(data["landing_page_url"].endswith(f"/in/{source.slug}/"))
        self.assertIn(f"source-{source.slug}.rss", data["feed_georss_url"])
