# Generated by Django 5.1.9 on 2025-10-15 10:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="openalex_fulltext_origin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="openalex_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="openalex_ids",
            field=models.JSONField(
                blank=True, help_text="OpenAlex IDs object (doi, pmid, etc)", null=True
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="openalex_is_retracted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publication",
            name="openalex_keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="openalex_match_info",
            field=models.JSONField(
                blank=True,
                help_text="Information about partial matches found",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="openalex_open_access_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="openalex_topics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("d", "Draft"),
                    ("p", "Published"),
                    ("t", "Testing"),
                    ("w", "Withdrawn"),
                    ("h", "Harvested"),
                    ("c", "Contributed"),
                ],
                default="success",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="status",
            field=models.CharField(
                choices=[
                    ("d", "Draft"),
                    ("p", "Published"),
                    ("t", "Testing"),
                    ("w", "Withdrawn"),
                    ("h", "Harvested"),
                    ("c", "Contributed"),
                ],
                default="d",
                max_length=1,
            ),
        ),
    ]
