# Generated by Django 5.1.7 on 2025-04-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="collection_name",
            field=models.CharField(
                blank=True,
                help_text="Identifier for a set or group of journals (e.g., 'Health Journals', 'TestBatch_Apr2025').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags to provide additional context",
                max_length=1024,
                null=True,
            ),
        ),
    ]
