# Generated by Django 5.1.7 on 2025-03-28 14:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["name"], "verbose_name": "subscription"},
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="search_area",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="user_name",
        ),
        migrations.AddField(
            model_name="subscription",
            name="region",
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscribed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(default="default_subscription", max_length=4096),
        ),
    ]
