# Generated by Django 5.1.9 on 2025-10-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Predefined geographic regions (continents and oceans)",
                related_name="subscriptions",
                to="publications.globalregion",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="search_term",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="timeperiod_enddate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="timeperiod_startdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
