# Generated by Django 5.1.7 on 2025-05-12 18:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_source_collection_name_source_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('issn_l', models.CharField(blank=True, max_length=9, null=True)),
                ('issn_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9), blank=True, default=list, size=None)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('openalex_id', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
