# Generated by Django 5.1.9 on 2025-05-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_source_collection_name_source_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='deleted_at',
        ),
    ]
