# Generated by Django 5.1.7 on 2025-05-25 15:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_source_collection_name_source_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "region_type",
                    models.CharField(
                        choices=[("C", "Continent"), ("O", "Ocean")], max_length=1
                    ),
                ),
                ("source_url", models.URLField()),
                ("license", models.CharField(max_length=200)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("last_loaded", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
