# Generated by Django 4.0.5 on 2023-11-21 08:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='timeperiod_enddate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='timeperiod_startdate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024, null=True), blank=True, null=True, size=None),
        ),
    ]
