# Generated by Django 5.1.7 on 2025-06-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0003_globalregion"),
        ("publications", "0003_remove_customuser_deleted_and_more"),
    ]

    operations = []
