# Generated by Django 4.0.5 on 2025-02-10 19:44

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_timeperiod_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
