# Generated by Django 5.1.7 on 2025-05-12 18:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of OpenAlex IDs (works) published in this journal', size=None),
        ),
    ]
