# Generated by Django 5.1.9 on 2025-10-17 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0004_rename_metadata_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="authors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                help_text="Author names (from original source or OpenAlex)",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                help_text="Keywords/subjects (from original source or OpenAlex)",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="topics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                help_text="Research topics (typically from OpenAlex)",
                null=True,
                size=None,
            ),
        ),
    ]
