# Generated by Django 5.1.9 on 2025-10-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0004_wikidata_export_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikidataexportlog",
            name="wikibase_endpoint",
            field=models.URLField(
                blank=True,
                help_text="Wikibase API endpoint used for this export (e.g., https://www.wikidata.org/w/api.php)",
                max_length=512,
                null=True,
            ),
        ),
    ]
