# Generated by Django 5.1.9 on 2025-05-20 07:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_journal_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of OpenAlex work IDs for this journal', size=None),
        ),
        migrations.AlterField(
            model_name='source',
            name='collection_name',
            field=models.CharField(blank=True, help_text='Identifier for a set or group of journals', max_length=255, null=True),
        ),
    ]
