# Generated by Django 4.0.5 on 2025-02-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_harvestingevent_alter_publication_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=1024, unique=True),
        ),
    ]
