# Generated by Django 5.1.9 on 2025-05-20 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_journal_articles_alter_source_collection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of OpenAlex work IDs', size=None),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn_l',
            field=models.CharField(blank=True, help_text='The primary ISSN (ISSN-L) — must be unique.', max_length=9, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('issn_l',), name='unique_issn_l'),
        ),
    ]
