# Generated by Django 4.0.5 on 2025-02-12 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0005_emaillog_sent_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['name'], 'verbose_name': 'subscription'},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='search_area',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='default_subscription', max_length=4096),
        ),
    ]
