# Generated by Django 5.1.9 on 2025-06-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_journal_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='openalex_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='works_api_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='works_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
