# Generated by Django 5.1.7 on 2025-03-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_blockeddomain_blockedemail'),
        ('publications', '0005_sentemaillog_sent_by'),
    ]

    operations = [
    ]
