# Generated by Django 5.1.9 on 2025-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_alter_journal_articles_alter_journal_issn_l_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journal',
            name='unique_issn_l',
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn_l',
            field=models.CharField(blank=True, help_text='The primary ISSN (ISSN-L) — must be unique.', max_length=9, null=True),
        ),
    ]
