# Generated by Django 5.1.7 on 2025-03-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_blockeddomain_blocked_by_blockedemail_blocked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=1024, unique=True),
        ),
    ]
