# Generated by Django 5.1.9 on 2025-05-27 10:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_remove_journal_unique_issn_l_alter_journal_issn_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Primary location for the journal (e.g., headquarters or office).', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn_l',
            field=models.CharField(blank=True, help_text='The primary ISSN (ISSN-L) — must be valid.', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='collection_name',
            field=models.CharField(blank=True, help_text="Identifier for a set or group of journals (e.g., 'Health Journals', 'TestBatch_Apr2025').", max_length=255, null=True),
        ),
    ]
