# Generated by Django 5.1.9 on 2025-05-27 14:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_journal_geometry_alter_journal_issn_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Primary coordinates for this journal', null=True, srid=4326),
        ),
    ]
