# Generated by Django 5.1.9 on 2025-05-27 19:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_alter_journal_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
