# Generated by Django 5.1.9 on 2026-05-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="first_page",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="issue",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="last_page",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="volume",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
