# Generated by Django 5.1.9 on 2026-05-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0002_work_journal_citation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="country_code",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-2 country code (or 3166-2 subdivision) for the geometry centroid.",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="placename",
            field=models.CharField(
                blank=True,
                help_text="Reverse-geocoded placename for the geometry centroid (Nominatim).",
                max_length=255,
                null=True,
            ),
        ),
    ]
