# Generated by Django 5.1.9 on 2026-04-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0002_recognition_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvestingevent",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="harvestingevent",
            name="log_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="harvestingevent",
            name="records_added",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="harvestingevent",
            name="records_with_spatial",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="harvestingevent",
            name="records_with_temporal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="harvestingevent",
            index=models.Index(
                fields=["source", "-started_at"], name="works_harve_source__6dc6fa_idx"
            ),
        ),
    ]
