# Generated by Django 5.1.9 on 2026-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0003_work_country_code_work_placename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("oai-pmh", "OAI-PMH (generic)"),
                    ("ojs", "OJS (Open Journal Systems)"),
                    ("janeway", "Janeway"),
                    ("rss", "RSS / Atom feed"),
                    ("crossref-prefix", "Crossref (DOI prefix)"),
                    ("mountain-wetlands", "Mountain Wetlands Repository"),
                    ("openalex", "OpenAlex source"),
                ],
                db_index=True,
                default="oai-pmh",
                help_text="Platform / API style of this source. Selects which harvester runs.",
                max_length=32,
            ),
        ),
    ]
