# Generated by Django 5.1.9 on 2026-05-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0004_alter_source_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="abbreviated_title",
            field=models.CharField(
                blank=True,
                help_text="Abbreviated journal title (display only).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="cited_by_count",
            field=models.IntegerField(
                blank=True,
                help_text="Auto-populated statistic (display only).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="homepage_url",
            field=models.URLField(
                blank=True,
                help_text="Public homepage of the journal/repository. Display only.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="is_oa",
            field=models.BooleanField(
                default=False,
                help_text="Display flag — marks the source as Open Access in admin lists. Does not affect harvesting.",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="is_preprint",
            field=models.BooleanField(
                default=False,
                help_text="Display flag — marks works from this source as preprints. Does not affect harvesting.",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="issn_l",
            field=models.CharField(
                blank=True,
                help_text="Linking ISSN (display only).",
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(
                help_text="Display name shown in the admin source list and on /pages, /sitemap.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="openalex_id",
            field=models.CharField(
                blank=True,
                help_text='OpenAlex Source identifier (e.g. "S4210203054"). REQUIRED when source_type=openalex (the harvester resolves it from openalex_id first, then openalex_url, then url_field — whichever contains an S<digits> token wins). Optional metadata for other source types.',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="openalex_url",
            field=models.URLField(
                blank=True,
                help_text="OpenAlex Source display URL (e.g. https://openalex.org/sources/S4210203054). Redundant for the harvester when openalex_id is filled — kept because the public Source API exposes it as the human-facing OpenAlex page link. Leave blank for a clean row; the harvester will not complain.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="publisher_name",
            field=models.CharField(
                blank=True,
                help_text="Display only — shown on the admin source detail page.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Free-form comma-separated tags for admin filtering. Display only.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="url_field",
            field=models.URLField(
                help_text='Source endpoint URL. What goes here depends on source_type — see docs/manage.md → "Source field cheatsheet". OAI-PMH: full ListRecords URL incl. metadataPrefix. RSS: feed URL. Crossref-prefix: display-only (the prefix is hard-coded to 10.5194 today, change requires code edit). Mountain-wetlands: API base URL. OpenAlex: any URL containing the S<id> works, or set openalex_id instead and put a placeholder here.',
                max_length=999,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="works_count",
            field=models.IntegerField(
                blank=True,
                help_text="Auto-populated statistic (display only).",
                null=True,
            ),
        ),
    ]
