# Generated by Django 5.1.9 on 2026-05-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0005_harvestingevent_records_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Default collection added to every work harvested from this source. Optional — leaving this blank is not an error: harvesting still succeeds, the works are simply not added to any collection (curators can add them later from each work landing page).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="works.collection",
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(fields=["status"], name="work_status_idx"),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["-creationDate", "-id"], name="work_creationdate_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                fields=["publicationDate"], name="work_publicationdate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=models.Index(
                condition=models.Q(("status", "p")),
                fields=["-creationDate", "-id"],
                name="work_published_recent_idx",
            ),
        ),
    ]
