# Generated by Django 5.1.9 on 2026-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0006_remove_source_openalex_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notify_work_events",
            field=models.BooleanField(
                default=True,
                help_text="Receive emails for work-state changes (contributions to review as an admin/curator, and 'your contribution was published' messages as a contributor). Opt-out — defaults to on so collaborators stay in the loop.",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="openalex_id",
            field=models.CharField(
                blank=True,
                help_text='OpenAlex Source identifier, e.g. "S4210203054" (or the full URL "https://openalex.org/S4210203054"). REQUIRED when source_type=openalex — the harvester scans this field first, then url_field, for an S<digits> token. The display URL (`openalex_url` in the public Source API) is derived from this.',
                max_length=50,
                null=True,
            ),
        ),
    ]
