# Generated by Django 5.1.9 on 2026-05-08 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0007_userprofile_notify_work_events_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="bok_concepts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                help_text="EO4GEO BoK concept codes contributed by users (resolved against the active BoK snapshot at render time).",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="kind",
            field=models.CharField(
                choices=[
                    ("spatial", "Spatial metadata"),
                    ("temporal", "Temporal metadata"),
                    ("ontology", "Ontology contributions"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
