# Generated by Django 5.1.9 on 2026-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0008_add_bok_concepts_and_ontology_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZenodoDepositionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposition_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "deposition_id",
                    models.CharField(
                        db_index=True, help_text="Zenodo deposition ID", max_length=50
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="DOI assigned by Zenodo (if published)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "zenodo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to Zenodo record",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "api_base",
                    models.URLField(
                        help_text="Zenodo API base URL (sandbox or production)",
                        max_length=512,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version string from last_version.txt",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "files_uploaded",
                    models.JSONField(
                        blank=True,
                        help_text="List of files uploaded (names and sizes)",
                        null=True,
                    ),
                ),
                (
                    "metadata_merged",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata fields that were updated",
                        null=True,
                    ),
                ),
                (
                    "works_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of works included in this deposition",
                    ),
                ),
                (
                    "total_size_bytes",
                    models.BigIntegerField(
                        default=0, help_text="Total size of uploaded files in bytes"
                    ),
                ),
                (
                    "upload_duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to upload all files",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if deposition failed",
                        null=True,
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed error information (stack trace, API response, etc.)",
                        null=True,
                    ),
                ),
                (
                    "deposition_summary",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable summary of the deposition",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or comments", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Zenodo Deposition Log",
                "verbose_name_plural": "Zenodo Deposition Logs",
                "ordering": ["-deposition_date"],
                "indexes": [
                    models.Index(
                        fields=["deposition_id"], name="works_zenodo_dep_id_idx"
                    ),
                    models.Index(fields=["doi"], name="works_zenodo_doi_idx"),
                ],
            },
        ),
    ]
