# Generated by Django 5.1.9 on 2026-06-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0011_add_published_works_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="abbreviated_title",
            field=models.CharField(
                blank=True,
                help_text="Abbreviated title (display only).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="homepage_url",
            field=models.URLField(
                blank=True,
                help_text="Public homepage of the source. Display only.",
                max_length=512,
                null=True,
            ),
        ),
    ]
