# Generated by Django 5.1.9 on 2026-06-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0013_userprofile_consented_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="doi_prefix",
            field=models.CharField(
                blank=True,
                help_text='DOI prefix used for Crossref-based harvesters (e.g. "10.1190" for SEG journals, "10.5194" for Copernicus). Used by source_type=crossref-prefix and source_type=geoscienceworld. Overrides the hardcoded fallback in harvest_crossref_prefix.',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("oai-pmh", "OAI-PMH (generic)"),
                    ("ojs", "OJS (Open Journal Systems)"),
                    ("janeway", "Janeway"),
                    ("rss", "RSS / Atom feed"),
                    ("crossref-prefix", "Crossref (DOI prefix)"),
                    ("mountain-wetlands", "Mountain Wetlands Repository"),
                    ("openalex", "OpenAlex source"),
                    ("geoscienceworld", "GeoScienceWorld"),
                ],
                db_index=True,
                default="oai-pmh",
                help_text="Platform / API style of this source. Selects which harvester runs.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="url_field",
            field=models.URLField(
                help_text='Source endpoint URL. What goes here depends on source_type — see docs/manage.md → "Source field cheatsheet". OAI-PMH: full ListRecords URL incl. metadataPrefix. RSS: feed URL. Crossref-prefix / GeoScienceWorld: display-only URL (harvester reads doi_prefix for the actual Crossref filter). Mountain-wetlands: API base URL. OpenAlex: any placeholder URL works as long as openalex_id is set to the S<id>; otherwise put a URL containing the S<id> here.',
                max_length=999,
            ),
        ),
    ]
