# Generated by Django 5.1.9 on 2026-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0014_source_doi_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvestingevent",
            name="records_skipped",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
