# Generated by Django 5.1.9 on 2026-06-12 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0015_harvesting_event_records_skipped"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("next_update", models.DateTimeField(blank=True, null=True)),
                ("total_works", models.IntegerField(default=0)),
                ("published_works", models.IntegerField(default=0)),
                ("harvested_works", models.IntegerField(default=0)),
                ("contributed_works", models.IntegerField(default=0)),
                ("with_geometry", models.IntegerField(default=0)),
                ("with_temporal", models.IntegerField(default=0)),
                ("with_complete_metadata", models.IntegerField(default=0)),
                ("complete_percentage", models.FloatField(default=0)),
                ("with_authors", models.IntegerField(default=0)),
                ("with_doi", models.IntegerField(default=0)),
                ("with_abstract", models.IntegerField(default=0)),
                ("open_access", models.IntegerField(default=0)),
                ("sources", models.IntegerField(default=0)),
                ("collections", models.IntegerField(default=0)),
                ("users", models.IntegerField(default=0)),
                ("contributors", models.IntegerField(default=0)),
                ("by_continent", models.JSONField(default=list)),
                ("by_ocean", models.JSONField(default=list)),
                ("by_country", models.JSONField(default=list)),
                ("by_publisher", models.JSONField(default=list)),
                ("by_journal", models.JSONField(default=list)),
                ("by_collection", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-computed_at"],
                "get_latest_by": "computed_at",
            },
        ),
        migrations.CreateModel(
            name="SourceCoverageSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "openalex_total",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("optimap_count", models.IntegerField(default=0)),
                (
                    "coverage_pct",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "spatial_rate",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "temporal_rate",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "open_access_ratio",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("contributors_count", models.IntegerField(default=0)),
                ("by_year", models.JSONField(default=list)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_snapshots",
                        to="works.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
                "get_latest_by": "computed_at",
            },
        ),
    ]
