# Generated by Django 5.1.9 on 2026-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0016_statistics_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_notified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="notification_interval",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                default="monthly",
                max_length=10,
            ),
        ),
    ]
