# Generated by Django 5.1.9 on 2026-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0017_subscription_notification_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="logo_url",
            field=models.URLField(
                blank=True,
                help_text="Optional external URL for a collection logo (no file upload). Displayed as a thumbnail on the collection landing page and index.",
                max_length=512,
                null=True,
            ),
        ),
    ]
