# Generated by Django 5.1.9 on 2026-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0019_rename_agile_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="statistics",
            field=models.JSONField(
                blank=True,
                help_text="Auto-populated harvest statistics. Stored as JSON; currently holds `openalex_works_count` (total works on OpenAlex for this source) and `openalex_fetched_at` (ISO-8601 timestamp of last fetch). Populated during harvesting whenever `openalex_id` is set.",
                null=True,
            ),
        ),
    ]
