# Generated by Django 5.1.9 on 2026-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0020_source_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="source_titles",
            field=models.JSONField(
                blank=True,
                help_text='Optional list of Crossref container-title filter values (e.g. ["Scientific Data"] or ["AGILE: GIScience Series"]). Required when doi_prefix covers multiple journals (e.g. 10.1038 = all Springer Nature) to restrict Crossref harvesting and stats to the target journal only. Leave blank for prefix-only sources (e.g. Copernicus 10.5194). Auto-populated from SOURCE_CONFIG; manual edits are preserved.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="statistics",
            field=models.JSONField(
                blank=True,
                help_text="Auto-populated harvest statistics. Stored as JSON; holds: `openalex_works_count` / `openalex_fetched_at` (OpenAlex, when openalex_id is set), `oai_works_count` / `oai_fetched_at` (OAI-PMH completeListSize, OAI source types only), `crossref_works_count` / `crossref_fetched_at` (Crossref rows=0 count, crossref-prefix type only). All timestamps are ISO-8601. Populated automatically after each harvest.",
                null=True,
            ),
        ),
    ]
