# Generated by Django 5.1.9 on 2026-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0021_source_titles"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("openaire", "OpenAIRE Graph API")],
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Long-lived refresh token pasted from the provider's token page. Rotating it resets the cached access token.",
                    ),
                ),
                ("refresh_token_set_at", models.DateTimeField(blank=True, null=True)),
                ("access_token", models.TextField(blank=True, default="")),
                (
                    "access_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service token",
                "verbose_name_plural": "Service tokens",
                "ordering": ["service"],
            },
        ),
    ]
