# Generated by Django 5.1.9 on 2026-06-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0022_servicetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="doi_contains",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Crossref-only: keep only works whose DOI contains this substring (case-insensitive). Use when a DOI prefix is shared by multiple venues — e.g. '10.22541' is shared by ESS Open Archive (.../essoar.*) and Authorea (.../au.*). Leave blank to keep all prefix matches.",
                max_length=50,
            ),
        ),
    ]
