# Generated by Django 5.1.9 on 2026-06-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0023_source_doi_contains"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="crossref_filter",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Crossref-only: raw Crossref filter clauses used as the harvest query instead of prefix:<doi_prefix>. Comma-separated, e.g. 'member:311,type:posted-content' for ESS Open Archive (whose two DOI eras — 10.1002/essoar.* and 10.22541/essoar.* — are only jointly captured by the Wiley member + posted-content slice, then narrowed with doi_contains). Leave blank to harvest by doi_prefix.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="doi_contains",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Crossref-only: keep only works whose DOI contains this substring (case-insensitive). Use when a Crossref query returns more than one venue — e.g. ESS Open Archive shares DOI prefixes and the Wiley member id with Authorea; doi_contains='essoar' keeps only ESSOAr (.../essoar.*). Leave blank to keep all query matches.",
                max_length=50,
            ),
        ),
    ]
