# Generated by Django 5.1.9 on 2026-06-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0024_source_crossref_filter_alter_source_doi_contains"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticssnapshot",
            name="contributed_dois",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="kind",
            field=models.CharField(
                choices=[
                    ("spatial", "Spatial metadata"),
                    ("temporal", "Temporal metadata"),
                    ("ontology", "Ontology contributions"),
                    ("doi", "Submitted works (DOI)"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
