# Generated by Django 5.1.9 on 2026-06-22 20:21

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0026_seed_user_contributions_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="locations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Hosting copies/versions of this work (from OpenAlex). Each entry carries a `credit` field.",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("d", "Draft"),
                    ("p", "Published"),
                    ("t", "Testing"),
                    ("w", "Withdrawn"),
                    ("h", "Harvested"),
                    ("c", "Contributed"),
                    ("r", "Redirected"),
                ],
                default="success",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="status",
            field=models.CharField(
                choices=[
                    ("d", "Draft"),
                    ("p", "Published"),
                    ("t", "Testing"),
                    ("w", "Withdrawn"),
                    ("h", "Harvested"),
                    ("c", "Contributed"),
                    ("r", "Redirected"),
                ],
                default="d",
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["openalex_ids"], name="work_openalex_ids_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="work",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["locations"], name="work_locations_gin"
            ),
        ),
    ]
