# Generated by Django 5.1.9 on 2026-06-22 21:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.utils.text import slugify


def backfill_source_slugs(apps, schema_editor):
    """Populate Source.slug for existing rows (unique, name-derived)."""
    Source = apps.get_model("works", "Source")
    used = set()
    for source in Source.objects.all().order_by("pk"):
        if source.slug:
            used.add(source.slug)
            continue
        base = slugify(source.name) or f"source-{source.pk}"
        candidate = base
        n = 2
        while candidate in used:
            candidate = f"{base}-{n}"
            n += 1
        source.slug = candidate
        source.save(update_fields=["slug"])
        used.add(candidate)


class Migration(migrations.Migration):
    dependencies = [
        ("works", "0027_work_locations_redirect"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "iso_code",
                    models.CharField(db_index=True, max_length=2, unique=True),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("last_loaded", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="source",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-safe identifier for the public /in/<slug>/ landing page and per-source feeds. Auto-generated from name when left blank.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(backfill_source_slugs, migrations.RunPython.noop),
    ]
