# Generated by Django 5.1.9 on 2026-06-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0028_country_source_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="continent",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Continent name (from Natural Earth), used to group the /countries/ overview.",
                max_length=50,
            ),
        ),
    ]
