# Generated by Django 5.1.9 on 2026-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0032_country_sentinel"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Global regions (continents and oceans) whose outline intersects the work's geometry (offline point-in-polygon join; multi-valued).",
                related_name="works",
                to="works.globalregion",
            ),
        ),
    ]
