# Generated by Django 5.1.9 on 2026-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0033_work_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="language",
            field=models.CharField(
                blank=True,
                help_text="ISO 639-2 alpha-3 language code (e.g. 'eng')",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="publisher",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
