# Generated by Django 5.1.9 on 2026-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0034_work_language_work_publisher"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseMapLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_key",
                    models.CharField(
                        help_text="leaflet-providers.js id, e.g. 'OpenStreetMap.Mapnik', 'CartoDB.Voyager'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display name shown in the map layer switcher.",
                        max_length=100,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Show this layer in the switcher for all visitors.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Layer shown on initial map load.  Exactly one enabled layer should be default.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Position in the layer switcher (lower = earlier).",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra options passed to L.tileLayer.provider(key, options), e.g. {'apiKey': '…'}.",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "label"],
            },
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="service",
            field=models.CharField(
                choices=[
                    ("openaire", "OpenAIRE Graph API"),
                    ("openalex", "OpenAlex API"),
                ],
                max_length=64,
                unique=True,
            ),
        ),
    ]
